// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using behaviac;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

namespace Example
{
///<<< BEGIN WRITING YOUR CODE NAMESPACE_INIT

///<<< END WRITING YOUR CODE

	public class NonPlayerCharacterAgent : Agent
///<<< BEGIN WRITING YOUR CODE NonPlayerCharacterAgent
///<<< END WRITING YOUR CODE
	{
        private NonPlayerCharacterBase npc;

        public NonPlayerCharacterAgent()
        {
        }

        public void InitAgent(NonPlayerCharacterBase character)
        {
            npc = character;
        }

        public EBTStatus CheckFindTarget()
		{
			return behaviac.EBTStatus.BT_INVALID;
		}

		public EBTStatus MoveToNextPoint()
		{
			return behaviac.EBTStatus.BT_INVALID;
		}

        public EBTStatus MoveToTarget()
        {
            return EBTStatus.BT_INVALID;
        }


        public EBTStatus TestVisible()
		{
			return EBTStatus.BT_INVALID;
		}
	}

}
