// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using behaviac;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

namespace Example
{
///<<< BEGIN WRITING YOUR CODE NAMESPACE_INIT

///<<< END WRITING YOUR CODE

	public class NonPlayerCharacterAgent : Agent
///<<< BEGIN WRITING YOUR CODE NonPlayerCharacterAgent
///<<< END WRITING YOUR CODE
	{
        private NonPlayerCharacterBase npc;
        private GameObject targetObj;

        public NonPlayerCharacterAgent()
        {
        }

        public void InitAgent(NonPlayerCharacterBase character)
        {
            npc = character;
        }

        public EBTStatus CheckFindTarget()
		{
            if(npc.CheckTargetAround(true, out targetObj))
            {
                return EBTStatus.BT_SUCCESS;
            }

			return EBTStatus.BT_FAILURE;
		}

		public EBTStatus MoveToNextPoint()
		{
            bool reached = npc.ArrivedAtTarget();
            if(reached)
            {
                npc.MoveToNext();

                return behaviac.EBTStatus.BT_SUCCESS;
            }
            else
            {
                return EBTStatus.BT_RUNNING;
            }
		}

        public EBTStatus MoveToTarget()
        {
            if(null != targetObj)
            {
                if(!npc.CheckArrivedTargetPosition())
                {
                    npc.MoveToPosition(targetObj.transform.position);
                    return EBTStatus.BT_SUCCESS;
                }
                else
                {
                    return EBTStatus.BT_RUNNING;
                }
            }

            return EBTStatus.BT_INVALID;
        }


        public EBTStatus TestVisible()
		{
			return EBTStatus.BT_INVALID;
		}
	}

}
